//
//  Tracks.swift
//  HoloRace
//
//  Created by Wiktor Jankowski on 28/04/2022.
//

import SwiftUI

struct Track: Identifiable {
    let id = UUID()
    var title: String
    var subtitle: String
    var text: String
    var image: String
    var background: String
    var logo: String
    var location: String
    var url: String
}

var tracks = [
    Track(title:"Innovation Park Zürich", subtitle: "Circuit Length - TBA", text:"Switzerland is a small mountainous country located in central Europe. This landlocked country is about the size of New Jersey and is between France and Italy. It is also bordered by Austria, Germany, and Liechtenstein.", image: "Hungary Layout",background: "Background Switzerland", logo:"Switzerland Flag",location:"Zürich, Switzerland", url: "https://maps.apple.com/?address=Wangenstrasse%2070,%208600%20D%C3%BCbendorf,%20Switzerland&auid=13867366743933577071&ll=47.404852,8.629932&lsp=9902&q=Switzerland%20Innovation%20Park%20Z%C3%BCrich&_ext=CiwKBQgEENMBCgQIBRADCgUIBhDfAQoECAoQAAoECFIQAwoECFUQDwoECFkQAhImKSe9b21Ds0dAMQ30tl0CPyFAOaWSlclptEdAQZsKMA3ORSFAUAQ%3D"),
    Track(title:"Hungaroring", subtitle: "Circuit Length - 4.381km", text:"Hungary in July is usually hot hot hot. The good news if you’re at the track, though, is that there’s a water park close by – the Mogyorodi Aquarena vizi szorakoztatopark – which should be a good place to cool off. Away from aqueous activities, the circuit is only 20km from Budapest, putting you close to one of Europe’s most fascinating, storied and lively city centres.", image: "Hungary Layout",background: "Background 17", logo:"Hungary Flag",location:"Budapest, Hungary", url: "https://maps.apple.com/?address=Hungaroring%20%C3%BAt%2010.,%202146%20Mogyor%C3%B3d,%20Hungary&auid=14252311146829654561&ll=47.582316,19.249849&lsp=9902&q=Tor%20Wy%C5%9Bcigowy%20Hungaroring&_ext=CjIKBQgEEIoBCgQIBRADCgUIBhDgAQoECAoQAgoECFIQDQoECFMQAwoECFUQCwoECFkQARIkKTusy4S6yUdAMXU5JSAmPTNAOSOTQg9ry0dAQWdwSi8gQjNA"),
    Track(title:"Bahrain International Circuit", subtitle: "Circuit Length - 5.412km", text:"Given the nature of the track, race-goers in Bahrain have always got a decent chance of being treated to a 'duel in the desert' or three. Away from the race track, Bahrain, as you might expect, is a great place to catch some rays, with the 33-island archipelago kingdom featuring some jaw-dropping resorts. And if you want to do some racing yourself, the Bahrain International Karting Circuit, located right next to the track, is one of the world’s top karting facilities.", image: "Bahrain Layout", background: "Background 15", logo:"Bahrain Flag", location: "Sakhir, Bahrain",url: "https://maps.apple.com/?address=Gate%20255,%20Gulf%20of%20Bahrain%20Avenue,%20Umm%20Jidar%201062,%20Sakhir,%20Bahrain&auid=10072879962212556904&ll=26.030347,50.514502&lsp=9902&q=Bahrain%20International%20Circuit&_ext=CisKBAgEEAwKBAgFEAMKBQgGEOABCgQIChAACgQIUhANCgQIVRALCgQIWRABEiQp9IsS9BcGOkAxZayRuCJBSUA5stwtJLsJOkBBGGJQAYtCSUA%3D"),
    Track(title:"Jeddah Corniche Circuit", subtitle: "Circuit Length - 6.174km", text:"Fast. Very fast. Average speeds around the Jeddah Corniche Circuit are around 250km/h – quicker than those at Silverstone, and second on the 2021 calendar only to Monza – aka ‘The Temple of Speed’. It is, quite simply, the fastest street circuit ever seen in Formula 1 – while the track also features the most corners on the calendar with 27, many of them quick, sinuous bends as the drivers wend their way along the Jeddah waterfront.", image: "SA Layout",background: "Background 16", logo:"SA Flag",location:"Jeddah, Saudi Arabia",url:"https://maps.apple.com/?address=2329%20Corniche%20Road,%20Al%20Shatia,%20Jeddah%2023612,%20Saudi%20Arabia&auid=7233659157508526259&ll=21.637110,39.103062&lsp=9902&q=Jeddah%20Corniche%20Circuit&_ext=CisKBAgEEBQKBAgFEAMKBQgGEOABCgQIChAACgQIUhADCgQIVRANCgQIWRABEiYppEDHa/ahNUAxz3RsRpuMQ0A5oOsSJEOkNUBBlfPZ8teNQ0BQBA%3D%3D"),
    Track(title:"Albert Park Circuit", subtitle: "Circuit Length - 5.278km", text:"Often found on lists of the world’s best cities, Melbourne is a blast all year round – and it only gets better when Formula Student rolls into town. There are bars and restaurants aplenty, you’re right by the beach, while the race’s appearance at the start of Australia’s autumn means the temperatures should be peachy.", image: "Australia Layout",background: "Background Australia", logo:"Australia Flag",location:"Melbourne, Australia",url:"https://maps.apple.com/?address=Albert%20Park%20Grand%20Prix%20Circuit,%20Albert%20Park%20VIC%203206,%20Australia&auid=4163601609789548402&ll=-37.850239,144.969749&lsp=9902&q=Albert%20Park%20Circuit&_ext=CjIKBAgEEBYKBAgFEAMKBQgGEOABCgQIChAACgQIUhADCgQIVRAOCgQIWRABCgUIpAEQARImKZYa6ztu7ULAMYr1jM7bHmJAORhFxd9H7ELAQdznDQE5H2JAUAQ%3D"),
    Track(title:"Autodromo Enzo e Dino Ferrari", subtitle: "Circuit Length - 4.909km", text:"Like neighbouring Mugello, Imola is nestled in a fantastic part of the world, with the Tuscan hills to the south, the Adriatic beaches to the east and the gastronomic delights of cities like Bologna, Parma and Modena to the west – as well as the F1 mecca that is Ferrari’s HQ in nearby Maranello. There’s also no getting around the fact that a visit to Imola is an opportunity for F1 fans to pay their respects to Ayrton Senna and Roland Ratzenberger, who lost their lives at the 1994 San Marino Grand Prix.", image: "Imola Layout",background: "Background Imola", logo:"Italy Flag", location: "Imola, Italy",url:"https://maps.apple.com/?address=Piazza%20Ayrton%20Senna%20da%20Silva,%201,%2040026%20Imola,%20Bologna,%20Italy&auid=7951441201591014820&ll=44.344626,11.716707&lsp=9902&q=Autodromo%20Internazionale%20Enzo%20e%20Dino%20Ferrari&_ext=CjMKBQgEEJABCgQIBRADCgUIBhDgAQoECAoQAAoECFIQDQoECFUQDAoECFkQAQoFCKQBEAESJClWoHE8+itGQDGyzwjb9GwnQDmFlnX/WCxGQEEXghyUMHMnQA%3D%3D"),
    Track(title:"Miami International Autodrome", subtitle: "Circuit Length - 5.412km", text:"A street-track spectacular. With the Hard Rock Stadium at its epicentre, the 5.41km layout will feature 19 corners, three straights, potential for three DRS zones, and an estimated top speed of 320km/h. There are elevation changes too, the main one found between Turns 13 and 16, with the track heading over an exit ramp and under various flyovers across uneven ground. The Turn 14-15 chicane, meanwhile, has an uphill approach, with a crest in the middle, and then drops down on exit.", image: "Miami Layout",background: "Background 18", logo:"USA Flag", location:"Miami, USA",url:"https://maps.apple.com/?address=347%20Don%20Shula%20Dr,%20Miami%20Gardens,%20FL%20%2033056,%20United%20States&auid=2387019895361349872&ll=25.958517,-80.238454&lsp=9902&q=Miami%20International%20Autodrome&_ext=CjMKBQgEEOIBCgQIBRADCgUIBhDgAQoECAoQAAoECFIQAwoECFUQDwoECFkQAgoFCKQBEAESJClN+9aJQ945QDEAA96trxVUwDlFo921egw6QEEA/SH+1QhUwA%3D%3D"),
    Track(title:"Circuit de Barcelona-Catalunya", subtitle: "Circuit Length - 4.675km", text:"You don’t need us to tell you that Barcelona is one of the world’s great cities, even if we just sort of did. Food, culture, beaches – it’s all there, making a Spanish Grand Prix holiday a properly attractive proposition.", image: "Spain Layout",background: "Background Spain", logo:"Spain Flag",location:"Barcelona, Spain",url:"https://maps.apple.com/?address=Camino%20Mas%20Moreneta,%2008160%20Montmelo,%20Barcelona,%20Spain&auid=3511468549145242965&ll=41.569489,2.257583&lsp=9902&q=Tor%20Wy%C5%9Bcigowy%20Circuit%20De%20Catalunya&_ext=CjMKBQgEEM4BCgQIBRADCgUIBhDgAQoECAoQAAoECFIQDQoECFUQCwoECFkQAQoFCKQBEAESJCkjPsEPGMhEQDFHnW/6aQICQDm0FrAuuMlEQEHftCrTeR4CQA%3D%3D"),
    Track(title:"Circuit de Monaco", subtitle: "Circuit Length - 3.337km", text:"Incredibly narrow and totally iconic. Nelson Piquet memorably described driving around Monaco as “like riding a bicycle around your living room”… which is fair. Despite that, it’s a challenge that nearly all drivers love, forcing them to put their skills on the line and rewarding millimetric accuracy. A holiday on the French Riviera, plus the chance to watch Formula Student cars pounding past places where Monegasques usually go to buy a pint of milk? It really is as fun as it sounds. On top of that, the chance to walk the track after a day’s hard lapping – or even enjoy your dinner on it at one of the terrasse bars – is not to be missed.", image: "Monaco Layout",background: "Background Monaco", logo:"Monaco Flag", location: "Monte Carlo, Monaco",url:"https://maps.apple.com/?address=Avenue%20de%20la%20Madone%204,%2098000%20Monte-Carlo,%20Monaco&auid=14196956545119252940&ll=43.734637,7.421298&lsp=9902&q=Circuit%20de%20Monaco&_ext=CisKBAgEEEcKBAgFEAMKBQgGEOABCgQIChAACgQIUhADCgQIVRANCgQIWRABEiYpydEii3XdRUAxU3gbnRKpHUA5R6dI55veRUBBx+CAvc21HUBQBA%3D%3D"),
    Track(title:"Baku City Circuit", subtitle: "Circuit Length - 6.003km", text:"A mixture of wide and open and tight and twisty. The lonnnnng main straight along the Baku shoreline is a slipstreaming mecca, and with cars able to run three abreast into Turn 1, the action often looks more IndyCar than Formula Student. However from there, the track loops around into the city’s narrow, winding Icheri Sheher old town, dramatically wending past Baku’s medieval city walls. As in Monaco, slightest mistakes are punished quickly and severely, while set-up wise, the teams are forced to choose between downforce for the twisty bits and less drag for the straight.", image: "Azerbaijan Layout",background: "Background Azerbaijan", logo:"Azerbaijan Flag",location:"Baku, Azerbaijan",url:"https://maps.apple.com/?address=Azadl%C4%B1q%20Meydan%C4%B1,%20Baku,%20Azerbaijan&auid=9977210826674678867&ll=40.372869,49.853103&lsp=9902&q=Baku%20City%20Circuit&_ext=CisKBAgEEFIKBAgFEAMKBQgGEOABCgQIChAACgQIUhADCgQIVRAOCgQIWRABEiYpCsyZQysvREAxi6OPKXXsSEA5iKG/n1EwREBBdVxwivftSEBQAw%3D%3D"),
    Track(title:"Circuit Gilles-Villeneuve", subtitle: "Circuit Length - 4.361km", text:"The fast, low-downforce circuit is one of the drivers’ favourites. The track is quite stop-start, with lots of heavy-braking chicanes and the famous hairpin to get the anchors working hard. Out of the corners, though, the track is quick and flowing, while the most iconic piece of the circuit comes right at the end of the lap: the Wall of Champions, so-called after excursions into it from Damon Hill, Jacques Villeneuve and Michael Schumacher during the 1999 Canadian Grand Prix weekend.", image: "Canada Layout", background: "Background Canada",logo:"Canada Flag", location:"Montreal, Canada",url:"https://maps.apple.com/?address=222%20Circt%20Gilles-Villeneuve,%20Parc%20Jean-Drapeau,%20Montr%C3%A9al%20QC%20H3C%206A1,%20Canada&auid=10885563534042444372&ll=45.501316,-73.522623&lsp=9902&q=Circuit%20Gilles-Villeneuve&_ext=CjIKBAgEEGIKBAgFEAMKBQgGEOABCgQIChAACgQIUhANCgQIVRALCgQIWRABCgUIpAEQARIkKSQyPFiktEZAMcnOo/+paVLAOWCKHzOty0ZAQTYxPFM7WVLA"),
    Track(title:"Silverstone Circuit", subtitle: "Circuit Length - 5.891km", text:"It’s hard to stop the goose bumps from prickling as you walk around one of the great cathedrals of motorsport, while in terms of atmosphere, the British fans are always reliably raucous – this is the country that invented football (that’s soccer, mind), after all.", image: "UK Layout",background: "Background UK", logo:"UK Flag",location:"Silverstone, UK",url:"https://maps.apple.com/?address=Towcester,%20NN12%208TN,%20England&auid=14441965028311635563&ll=52.072529,-1.014562&lsp=9902&q=Tor%20Wy%C5%9Bcigowy%20Silverstone&_ext=CjkKBQgEEOEBCgQIBRADCgUIBhDgAQoECAoQAAoECFIQDQoECFMQAwoECFUQCgoECFkQAQoFCKQBEAESJCmtXFqTxP1JQDEA7zoVkpLyvznBPPbIxhRKQEEAH4rVb8nrvw%3D%3D"),
    Track(title:"Red Bull Ring", subtitle: "Circuit Length - 4.318km", text:"Race tracks don’t come much more picturesque than the Red Bull Ring, set in an idyllic natural bowl in the Styrian mountains. That makes for a pleasant environment for a Grand Prix, while if you’re after tourist attractions to visit after the race, look no further than the museum in Graz dedicated to the city’s favourite son: Arnold Schwarzenegger.", image: "Austria Layout",background: "Background Austria", logo:"Austria Flag",location: "Spielberg, Austria",url:"https://maps.apple.com/?address=Red-Bull-Ring-Stra%C3%9Fe%201,%208724%20Spielberg,%20Austria&auid=1288249379815938812&ll=47.220151,14.763994&lsp=9902&q=Red%20Bull%20Ring&_ext=CisKBAgEEFEKBAgFEAMKBQgGEOABCgQIChABCgQIUhADCgQIVRAMCgQIWRABEiYpiDwNVqWbR0AxukcmzL+DLUA5BhIzssucR0BBNidma4WKLUBQBA%3D%3D"),
    Track(title:"Circuit Paul Ricard", subtitle: "Circuit Length - 5.842km", text:"Drive just 10km south of the circuit and you’ll find yourself on the French Riviera, one of the most revered coastlines in the world thanks to its beautiful beaches, pretty harbourside towns, great food and, if you fancy it, incredible local wines. Apart from the racing action, that’s why you go!", image: "France Layout",background: "Background France", logo:"France Flag",location:"Le Castellet, France",url:"https://maps.apple.com/?address=2760%20Route%20des%20Hauts%20du%20Camp,%2083330%20Le%20Castellet,%20France&auid=17249621374726992197&ll=43.251706,5.793383&lsp=9902&q=Tor%20Wy%C5%9Bcigowy%20Circuit%20Paul-ricard&_ext=CisKBAgEEHoKBAgFEAMKBQgGEOABCgQIChACCgQIUhANCgQIVRALCgQIWRABEiQpWbqhJLCURUAxoDL2IN+tFkA57eCTTrurRUBBYM0J6PmqF0A%3D")

]

var featuredTracks = [
    Track(title:"Hungaroring", subtitle: "Circuit Length - 4.381km", text:"Hungary in July is usually hot hot hot. The good news if you’re at the track, though, is that there’s a water park close by – the Mogyorodi Aquarena vizi szorakoztatopark – which should be a good place to cool off. Away from aqueous activities, the circuit is only 20km from Budapest, putting you close to one of Europe’s most fascinating, storied and lively city centres.", image: "Hungary Layout",background: "Background 17", logo:"Hungary Flag",location:"Budapest, Hungary",url:""),
    Track(title:"Albert Park Circuit", subtitle: "Circuit Length - 5.278km", text:"Often found on lists of the world’s best cities, Melbourne is a blast all year round – and it only gets better when Formula Student rolls into town. There are bars and restaurants aplenty, you’re right by the beach, while the race’s appearance at the start of Australia’s autumn means the temperatures should be peachy.", image: "Australia Layout",background: "Background Australia", logo:"Australia Flag",location:"Melbourne, Australia",url:""),
    Track(title:"Circuit de Monaco", subtitle: "Circuit Length - 3.337km", text:"Incredibly narrow and totally iconic. Nelson Piquet memorably described driving around Monaco as “like riding a bicycle around your living room”… which is fair. Despite that, it’s a challenge that nearly all drivers love, forcing them to put their skills on the line and rewarding millimetric accuracy. A holiday on the French Riviera, plus the chance to watch Formula Student cars pounding past places where Monegasques usually go to buy a pint of milk? It really is as fun as it sounds. On top of that, the chance to walk the track after a day’s hard lapping – or even enjoy your dinner on it at one of the terrasse bars – is not to be missed.", image: "Monaco Layout",background: "Background Monaco", logo:"Monaco Flag", location:"Monte Carlo, Monaco",url:""),
    Track(title:"Circuit Gilles-Villeneuve", subtitle: "Circuit Length - 4.361km", text:"The fast, low-downforce circuit is one of the drivers’ favourites. The track is quite stop-start, with lots of heavy-braking chicanes and the famous hairpin to get the anchors working hard. Out of the corners, though, the track is quick and flowing, while the most iconic piece of the circuit comes right at the end of the lap: the Wall of Champions, so-called after excursions into it from Damon Hill, Jacques Villeneuve and Michael Schumacher during the 1999 Canadian Grand Prix weekend.", image: "Canada Layout", background: "Background Canada",logo:"Canada Flag",location:"Montreal, Canada",url:""),
    Track(title:"Silverstone Circuit", subtitle: "Circuit Length - 5.891km", text:"It’s hard to stop the goose bumps from prickling as you walk around one of the great cathedrals of motorsport, while in terms of atmosphere, the British fans are always reliably raucous – this is the country that invented football (that’s soccer, mind), after all.", image: "UK Layout",background: "Background UK", logo:"UK Flag",location:"Silverstone, UK",url:"")
    

]
